title: Duan Junwen's Homepage
page-top-title: Duan Junwen
top-section-bg-text: Computer Science
home-subtitle: Duan Junwen&ensp;|&ensp;段俊文
copyright-text: '&copy; Duan Junwen 2024-2025. All Rights Reserved.'
